id: ian-whitney-blog-post-rust-via-its-core-values-cited
name: Ian Whitney
influence:
- evidence: 'quoted as TWiR "Quote of the Week" on two separate occasions two years apart: by @nayru25 (2016-04-03) and re-cited by @cg-cnu (2018-04-25)'
  url: https://users.rust-lang.org/t/twir-quote-of-the-week/328/1681
  date: '2016-04-03'
